name: POPUtils
version: 1.0
description: Utilities for PrisonPOP
main: me.DMan16.POPUtils.POPUtilsMain
depend: [POPUpdater]
softdepend: [Vault,WorldEdit,WorldGuard,PlaceholderAPI,Citizens,POPEconomy,ProtocolLib,ViaVersion,Essentials]
author: DMan16
api-version: 1.17

commands:
  versions:
    permission: prisonpop.command.versions
  restrictions:
    permission: prisonpop.command.restrictions
  item:
    permission: prisonpop.command.item
  test_effect:
    permission: prisonpop.command.test_effect
permissions:
  prisonpop.command.versions:
    default: op
  prisonpop.command.restrictions:
    default: op
  prisonpop.command.item:
    default: op
  prisonpop.command.test_effect:
    default: op