name: DMan16Utils
version: 1.0
description: Utilities by DMan16
main: me.DMan16.DMan16Utils.DMan16UtilsMain
depend: [DMan16Updater]
softdepend: [Vault,WorldEdit,WorldGuard,PlaceholderAPI,Citizens,ProtocolLib,ViaVersion]
author: DMan16
api-version: 1.17

commands:
  versions:
    permission: dman16.command.versions
  restrictions:
    permission: dman16.command.restrictions
  item:
    permission: dman16.command.item
  book:
    permission: dman16.command.book
  enchant:
    permission: dman16.command.enchant
  damage:
    permission: dman16.command.damage
  repair:
    permission: dman16.command.repair
  fix:
    permission: dman16.command.fix
  uuid:
    permission: dman16.command.uuid
  test_effect:
    permission: dman16.command.test_effect
permissions:
  dman16.command.versions:
    default: op
  dman16.command.restrictions:
    default: op
  dman16.command.item:
    default: op
  dman16.command.book:
    default: op
  dman16.command.enchant:
    default: op
  dman16.command.damage:
    default: op
  dman16.command.repair:
    default: op
  dman16.command.fix:
    default: op
  dman16.command.uuid:
    default: op
  dman16.command.test_effect:
    default: op