name: POPUtils
version: 1.0
description: Utilities for PrisonPOP
main: me.DMan16.POPUtils.POPUtils
depend: [POPUpdater]
softdepend: [Vault,WorldGuard,PlaceholderAPI,Citizens,POPEconomy,ProtocolLib,ViaVersion]
author: DMan16
api-version: 1.17

commands:
  versions:
    permission: prisonpop.command.versions
permissions:
  prisonpop.command.versions:
    default: op