name: POPUtils
version: 1.0
description: Utilities for PrisonPOP
main: me.DMan16.POPUtils.POPUtilsMain
depend: [POPUpdater]
softdepend: [Vault,WorldGuard,PlaceholderAPI,Citizens,POPEconomy,ProtocolLib]
author: DMan16
api-version: 1.17